/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Array;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  @DisplayName("test normal")
  void test1(){

      int[] arr={8,4,23,42,16,15};
      App.insertionSort(arr);

      int[] exp={4,8,15,16,23,42};
      assertEquals(Arrays.toString(exp),Arrays.toString(arr));


  }

    @Test
    @DisplayName("test empty array")
    void test2(){

        int[] arr={};
        App.insertionSort(arr);

        int[] exp={};
        assertEquals(Arrays.toString(exp),Arrays.toString(arr));


    }
}
