/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge18;

public class App {


    public static void main(String[] args) {

//        BinaryTree<Integer> binaryTree=new BinaryTree<>();
//
//        binaryTree.setRoot(new Node<>(1));
//
//        binaryTree.getRoot().setLeftNode(new Node<>(2));
//        binaryTree.getRoot().setRightNode(new Node<>(3));
//
//        binaryTree.getRoot().getLeftNode().setLeftNode(new Node<>(5));
//        binaryTree.getRoot().getLeftNode().setRightNode(new Node<>(15));
//
//
//        binaryTree.fizzBuzzTree(binaryTree).preorderDepthFirst();

        BinarySearchTree<Integer> binarySearchTree=new BinarySearchTree<>();
        binarySearchTree.insert(2);
        binarySearchTree.insert(7);
        binarySearchTree.insert(5);
        binarySearchTree.insert(3);
        binarySearchTree.insert(6);

        System.out.println( binarySearchTree.sumOfOdds(binarySearchTree.getRoot()));

        System.out.println(binarySearchTree.search(1));


//        binarySearchTree.oddSum(new Node<>(1));
        binarySearchTree.inorder1();



    }
}
