/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge18;

public class App {


    public static void main(String[] args) {

        BinaryTree<Integer> binaryTree=new BinaryTree<>();

        binaryTree.setRoot(new Node<>(1));

        binaryTree.getRoot().setLeftNode(new Node<>(2));
        binaryTree.getRoot().setRightNode(new Node<>(3));

        binaryTree.getRoot().getLeftNode().setLeftNode(new Node<>(5));
        binaryTree.getRoot().getLeftNode().setRightNode(new Node<>(15));


        binaryTree.fizzBuzzTree(binaryTree).preorderDepthFirst();



    }
}
