/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {

        int[] arr={};
        insertionSort(arr);
        System.out.println(Arrays.toString(arr));
    }


    public static void insertionSort(int[] arr){
        for (int i=1 ;i<arr.length;i++){
           int j=i-1;
           int temp=arr[i];

           while (j>=0 && temp<arr[j]){
               arr[j+1]=arr[j];
               j=j-1;
           }
           arr[j+1]=temp;
        }
    }
}
