/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

import challenge10.Queue.Queue;
import challenge10.stack.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Stack<Integer> stack=new Stack<>();

        stack.push(1);
        stack.push(2);
        stack.push(5);
        stack.push(6); //top element
//        if(stack.isEmpty()){
//            System.out.println("Empty stack");
//        }else {
//
//            System.out.println(stack);
//        }
//
//        System.out.println(stack.peek());
//        System.out.println(stack.pop());

        ////////////////////////////////////////////////// queue //////////////////////////////////////////

        Queue<Integer> queue=new Queue<>();
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);


        System.out.println(queue);

        System.out.println(queue.dequeue());








//        java.util.Stack<Integer>stack1=new java.util.Stack<>();
//        stack1.pop();
    }
}
