/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge12;

import challenge12.AnimalShelter.AnimalShelter;
import challenge12.AnimalShelter.Cat;
import challenge12.AnimalShelter.Dog;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        AnimalQueue animalQueue=new AnimalQueue();

        animalQueue.enqueue(new Dog("dog1","black1",5));
        animalQueue.enqueue(new Dog("dog2","black2",5));
        animalQueue.enqueue(new Dog("dog3","black3",5));
        animalQueue.enqueue(new Cat("tom1","gray1",3));
        animalQueue.enqueue(new Cat("tom2","gray2",3));
        animalQueue.enqueue(new Cat("tom3","gray3",3));
        System.out.println(animalQueue);
//        //if you want to dequeue cat pass cat as argument
        System.out.println(animalQueue.dequeue("cat"));
//
//        //if you want to dequeue cat pass dog as argument
        System.out.println(animalQueue.dequeue("dog"));


    }
}
