/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge13;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test
    @DisplayName("validate string with one bracket")
    public void test(){
       ValidateBrackets validateBrackets=new ValidateBrackets();
       assertFalse(validateBrackets.isValidateBrackets("["));
   }

    @Test
    @DisplayName("validate string with two bracket")
    public void test1(){
        ValidateBrackets validateBrackets=new ValidateBrackets();
        assertTrue(validateBrackets.isValidateBrackets("[]"));
    }

    @Test
    @DisplayName("validate string with word")
    public void test2(){
        ValidateBrackets validateBrackets=new ValidateBrackets();
        assertTrue(validateBrackets.isValidateBrackets("[hello]"));
    }

    @Test
    @DisplayName("validate string with multi")
    public void test3(){
        ValidateBrackets validateBrackets=new ValidateBrackets();
        assertTrue(validateBrackets.isValidateBrackets("{()}[hel{}lo]{()}"));
    }

    @Test
    @DisplayName("validate string with two different")
    public void test4(){
        ValidateBrackets validateBrackets=new ValidateBrackets();
        assertFalse(validateBrackets.isValidateBrackets("{]"));
    }

    @Test
    @DisplayName("validate string is null")
    public void test5(){
        ValidateBrackets validateBrackets=new ValidateBrackets();
        assertFalse(validateBrackets.isValidateBrackets(" "));
    }
}
