/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

public class App {

    public static void main(String[] args) {



        LinkedList<Integer>linkedList=new LinkedList<>();
        linkedList.insert(1);


        System.out.println(linkedList);
        System.out.println(linkedList.size());



        System.out.println(linkedList.KthFromEnd(0));

    }
}
