/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge18;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

//    @Test
//    @DisplayName("fizzbuzz tree test")
//    public void test01(){
//        BinaryTree<Integer> binaryTree=new BinaryTree<>();
//
//        binaryTree.setRoot(new Node<>(1));
//
//        binaryTree.getRoot().setLeftNode(new Node<>(2));
//        binaryTree.getRoot().setRightNode(new Node<>(3));
//
//        binaryTree.getRoot().getLeftNode().setLeftNode(new Node<>(5));
//        binaryTree.getRoot().getLeftNode().setRightNode(new Node<>(15));
//
//
//       ArrayList<String> result= binaryTree.fizzBuzzTree(binaryTree).preorderDepthFirst();
//       ArrayList<String> exp=new ArrayList<>();
//       exp.add("1");
//       exp.add("2");
//       exp.add("Buzz");
//       exp.add("FizzBuzz");
//       exp.add("Fizz");
//
//       assertEquals(exp,result);
//    }

//    @Test
//    @DisplayName("fizzbuzz tree empty test")
//    public void test02(){
//        BinaryTree<Integer> binaryTree=new BinaryTree<>();
//
//
//        ArrayList<String> result= binaryTree.fizzBuzzTree(binaryTree).preorderDepthFirst();
//        ArrayList<String> exp=new ArrayList<>();
//
//        assertEquals(exp,result);
//    }
}
