/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        MaxStack maxStack=new MaxStack();
        maxStack.push(1);
        maxStack.push(2);
        maxStack.push(3);
        maxStack.push(4);
        maxStack.pop();

        System.out.println(maxStack.max());
    }
}
