/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge35;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Graph graph=new Graph();
        System.out.println(graph.addNode("A"));
        graph.addNode("B");
        graph.addNode("C");
        graph.addNode("D");
        graph.addNode("E");
        graph.addNode("F");
        graph.addNode("G");
        graph.addNode("H");

        graph.addEdge("A","D");
        graph.addEdge("A","B");

        graph.addEdge("B","C");
        graph.addEdge("B","D");

        graph.addEdge("G","C");

        graph.addEdge("D","F");
        graph.addEdge("D","H");
        graph.addEdge("D","E");

        graph.addEdge("F","H");


        String[] arr={"A","B","C"};
        System.out.println(graph.depthFirst("F"));
    }
}
