/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge35;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Graph graph=new Graph();

        graph.addNode("A");


    }
}
