/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        System.out.println(new App().getGreeting());

        LinkedList<Integer> linkedList=new LinkedList<>();
        linkedList.insert(1);
        linkedList.insert(2);
        System.out.println(linkedList.includes(100));
        linkedList.print();
        linkedList.insert(55);
        System.out.println(linkedList.toString());

        System.out.println("///////////////////////////////////////////////////////////////////////////////////////////");

        LinkedList<String> str=new LinkedList<>();


    }
}
